global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'blackbox_health'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://frontend:80/
          - http://backend:3000/api/health
    relabel_configs:
      # URL en parametre
      - source_labels: [__address__]
        target_label: __param_target
      # URL dans le label instance
      - source_labels: [__param_target]
        target_label: instance
      # Redirection vers le blackbox exporter
      - target_label: __address__
        replacement: blackbox-exporter:9115
