name: Build and push Docker images

on:
  push:
    branches:
      - main
env:
  path: /home/admin/app
  compose_override: docker-compose-prod
  tag: sha-${{ github.sha }}-main
jobs:
  env:
    registry:
  docker:
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest
    steps:
      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v5

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:backend"
          push: true
          tags:
            - ${{env.REGISTRY}}/backend:${{env.tag}}
            - ${{env.REGISTRY}}/backend:latest-main
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:frontend"
          push: true
          tags:
            - ${{env.REGISTRY}}/frontend:${{env.tag}}
            - ${{env.REGISTRY}}/frontend:latest-main
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Copy compose to vps
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: admin
          key: ${{ secrets.SSH_KEY }}
          port: ${{secrets.SSH_PORT}}
          source: "docker-compose.yml,${{env.compose_override}}"
          target: "${{env.path}}"

      - name: Pull on vps
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: admin
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd ${{env.path}}
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            echo ${{env.tag}} > .env
            docker compose pull
            docker compose -f docker-compose.yml -f ${{env.compose_override}} up -d
            docker image prune -f
